### PR TITLE
Sirupsen -> sirupsen

### PR DESCRIPTION
**Pull request by wzhliang**
logrus has changed package naming from `Sirupsen` to `sirupsen`

https://github.com/sirupsen/logrus/pull/384

### CODE REVIEW

**Comment by ldez** [comment]
Sorry for this ping, but do you have plan to merge this PR?

**Comment by sylr** [comment]
@alena1108 @leodotcloud @cloudnautique @ibuildthecloud Sorry guys for the ping but this PR really need to be merged cause otherwise go mod becomes almost unusable if your package is referenced.

**Comment by leodotcloud** [comment]
@sylr With the release of Rancher 2.0, development on v1.6 is only limited to critical bug fixes and security patches.

Also, this repo is vendored in multiple microservices of 1.6.x. Merging this PR means, we will have to update all those microservices, make new releases, test them, etc ... 

My recommendation is to fork this repo and use it the way you want.

**Comment by sylr** [comment]
@leodotcloud it's maybe not a critical bug for rancher but it is for every other projects that comes to include (directly or indirectly) go-rancher-metadata and use the new logrus url at the same time.

I already did what you recommand but really, for the sake of others, please merge this, it has absolutely no impact for you and saves a great deal of troubles for others.

**Comment by ldez** [comment]
The merge of this PR will not be enough to remove the dependency: it is also necessary to migrate the dependencies of this project, for example https://github.com/rancher/rancher-metadata.

**Pull request merged**
